CREATE OR REPLACE VIEW pos_reference_codes AS
SELECT 'STORE_CATEGORY' AS category, 'BREAKFAST' AS code
UNION ALL SELECT 'STORE_CATEGORY', 'DINING'
UNION ALL SELECT 'STORE_CATEGORY', 'BAR'
UNION ALL SELECT 'STORE_CATEGORY', 'CAFE'
UNION ALL SELECT 'STORE_CATEGORY', 'LOUNGE'
UNION ALL SELECT 'SERVICE_PERIOD', 'BREAKFAST'
UNION ALL SELECT 'SERVICE_PERIOD', 'LUNCH'
UNION ALL SELECT 'SERVICE_PERIOD', 'AFTERNOON'
UNION ALL SELECT 'SERVICE_PERIOD', 'DINNER'
UNION ALL SELECT 'SERVICE_PERIOD', 'LATE_NIGHT';
