import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

function source(relativePath) {
  return readFileSync(new URL(`../../${relativePath}`, import.meta.url), "utf8");
}

const app = source("app/frontend/src/App.jsx");
const flags = source("app/frontend/src/features/reports/reportBuilderFlags.js");
const controller = source("app/frontend/src/features/reports/useReportsPageController.jsx");
const page = source("app/frontend/src/pages/ReportsPage.jsx");
const toolbar = source("app/frontend/src/features/reports/components/ReportEditorToolbar.jsx");
const toolPanel = source("app/frontend/src/features/reports/components/ReportToolPanel.jsx");
const properties = source("app/frontend/src/features/reports/components/ReportPropertiesPanel.jsx");
const assistant = source("app/frontend/src/features/reports/components/ReportAssistantPanel.jsx");
const builder = source("app/frontend/src/features/reports/v2/ReportBuilderV2.jsx");
const builderStyles = source("app/frontend/src/features/reports/v2/report-builder-v2.css");
const shortcutHelp = source("app/frontend/src/features/reports/v2/ReportShortcutHelp.jsx");
const presentation = source("app/frontend/src/features/reports/v2/ReportPresentation.jsx");
const canvas = source("app/frontend/src/features/reports/ReportPageCanvas.jsx");
const viewport = source("app/frontend/src/features/reports/reportEditorViewport.ts");
const normalization = source("app/frontend/src/contracts/reportNormalization.ts");

assert.match(flags, /VITE_REPORT_BUILDER_V2 !== "false"/);
assert.doesNotMatch(flags, /SHOWCASE/);
assert.doesNotMatch(app, /ReportAssistantShowcase|REPORT_ASSISTANT_SHOWCASE/);
assert.match(app, /reportEditorMode && REPORT_BUILDER_V2 \? "report-builder-v2-mode"/);
assert.doesNotMatch(controller, /REPORT_REVIEW_MODE|reviewDefinition|mockReport/i);
assert.match(page, /page\.builderV2 \? <ReportBuilderV2/);
assert.match(builder, /data-report-builder="v2"/);
assert.match(builder, /report-builder-v2-layout/);
assert.match(builder, /builder-library-column/);
assert.match(builder, /builder-workspace/);
assert.match(builder, /requestFullscreen/);
assert.match(builder, /pages\.map/);
assert.match(builder, /<ReportShortcutHelp/);
assert.match(builder, /\{presentation\}/);
assert.match(builder, /rightPanel === "assistant"/);
assert.match(builder, /className="builder-inspector"/);
assert.match(builderStyles, /\[data-report-builder="v2"\] \.report-builder-v2-layout/);
assert.match(builderStyles, /grid-template-columns:var\(--builder-library\) minmax\(620px,1fr\) var\(--builder-properties\)/);
assert.match(builderStyles, /\[data-report-builder="v2"\] \.report-properties-panel\{[^}]*display:block/);
assert.match(builderStyles, /@media\(max-width:1179px\)/);
assert.match(builderStyles, /@media\(max-width:900px\)/);
assert.match(builderStyles, /\.answer-report-canvas--editor\{padding:0/);
assert.match(builderStyles, /\.answer-report-page__block:has\(>\.selected\)/);
assert.match(builderStyles, /\.notion-block>\.report-block-chrome/);
assert.match(builderStyles, /\.report-shortcut-dialog/);
assert.match(builderStyles, /\.report-presentation/);
assert.doesNotMatch(builderStyles, /^\.notion-report-editor/m);
assert.match(canvas, /data-report-page-index=\{pageIndex\}/);
assert.match(canvas, /resolveReportEditorScale/);
assert.match(viewport, /fit-width/);
assert.match(viewport, /fit-page/);
assert.match(page, /draft\.addTemplateBlock\("artifact-chart", null, \{ chartType \}\)/);
assert.match(page, /onAddChart=\{addChartBlock\}/);
assert.match(page, /<ReportPresentation/);
assert.match(page, /renderBlock=\{page\.renderPreviewBlock\}/);
assert.match(shortcutHelp, /현재 draft를 서버에 저장/);
assert.match(shortcutHelp, /onKeyDown=\{\(event\) =>/);
assert.match(shortcutHelp, /event\.stopPropagation\(\)/);
assert.doesNotMatch(shortcutHelp, /Alt\+휠|목업|Mock/);
assert.match(presentation, /createPortal\(overlay, document\.body\)/);
assert.match(presentation, /pageCountOverride=\{pageCount\}/);
assert.match(presentation, /event\.key === " " && event\.target\.closest\?\./);
assert.match(presentation, /onKeyDown=\{navigate\}/);
assert.match(presentation, /event\.stopPropagation\(\)/);
assert.match(presentation, /ref=\{triggerRef\}/);
assert.match(presentation, /triggerRef\.current\?\.focus\(\)/);
assert.doesNotMatch(presentation, /document\.addEventListener\("keydown"/);
assert.match(builder, /ref=\{shortcutTriggerRef\}/);
assert.doesNotMatch(presentation, /mock|월간 경영|호텔 매출/i);
assert.match(toolbar, /보고서 확대 축소/);
assert.match(toolbar, /role="region" aria-label="편집 명령\. 작은 화면에서는 좌우로 스크롤할 수 있습니다\." tabIndex=\{0\}/);
assert.match(toolbar, /builderV2 \? "Preview" : "HTML 초안 확인"/);
assert.match(toolbar, /\{!builderV2 && <span className="notion-status-chip">/);
assert.match(builderStyles, /\.editor-command-actions\{[^}]*flex-wrap:nowrap/);
assert.match(toolPanel, /report-template-grid/);
assert.match(builderStyles, /\.report-template-grid\{grid-template-columns:1fr\}/);
assert.match(builderStyles, /\.report-library-search\{margin:14px 14px 2px\}/);
assert.match(builderStyles, /\.editor-view-actions \.report-orientation-switch\{[^}]*box-shadow:none/);
assert.match(builderStyles, /\.report-orientation-switch button\[aria-pressed="true"\]\{[^}]*background:#eaf3ff!important/);
assert.match(builderStyles, /\.answer-report-page \.notion-markdown-input\{min-height:42px!important/);
assert.match(builderStyles, /\.answer-report-page \.report-markdown-toolbar\{min-height:32px/);
assert.match(builderStyles, /\.answer-report-page \.report-markdown-hint\{display:none\}/);
assert.match(toolPanel, /REPORT ELEMENTS/);
assert.match(toolPanel, /보고서 블록 검색/);
assert.match(toolPanel, /REPORT_CHART_OPTIONS\.map/);
assert.match(properties, /const blockLocked =/);
assert.match(properties, /disabled=\{!canEdit \|\| blockLocked\}/);
assert.match(assistant, /onSubmit\(text\)/);
assert.match(page, /artifactTitle=\{page\.selectedArtifactSource\?\.title\}/);
assert.match(assistant, /artifactTitle \|\| "분석 Artifact를 선택해 주세요"/);
assert.match(assistant, /AI 초안 반영 완료/);
assert.match(assistant, /trace\.model_version/);
assert.match(assistant, /request_user_approval|새 데이터 분석 승인 필요/);
assert.match(assistant, /onApproveDataRequest/);
assert.match(assistant, /Revision 저장 재개/);
assert.match(assistant, /report-assistant-patch-items/);
assert.match(assistant, /selectedIndexes/);
assert.match(assistant, /onApprove\(selectedIndexes\)/);
assert.match(assistant, /useId\(\)/);
assert.match(assistant, /htmlFor=\{inputId\}/);
assert.match(assistant, /전체 선택/);
assert.match(assistant, /전체 해제/);
assert.match(assistant, /개 선택/);
assert.match(assistant, /<details className="report-assistant-patch-detail">/);
assert.match(assistant, /내용 펼치기/);
assert.match(assistant, /approvalRef\.current\?\.focus\(\)/);
assert.match(assistant, /PATCH_IMPACT_LABEL/);
assert.match(assistant, /선택한 변경 영향/);
assert.match(assistant, /preview\.items\.filter\(\(item\) => selectedIndexes\.includes\(item\.index\)\)/);
assert.match(assistant, /evidenceRequired/);
assert.match(assistant, /impactCategories\.includes\("DESTRUCTIVE"\)/);
assert.match(assistant, /새 Revision으로 저장되어 이전 버전을 유지합니다/);
assert.match(builderStyles, /:focus-visible/);
assert.match(builderStyles, /@media\(prefers-reduced-motion:reduce\)/);
assert.match(builderStyles, /@media\(max-width:480px\)/);
assert.match(builderStyles, /grid-template-columns:repeat\(auto-fit/);
assert.match(page, /approvedIndexes: lifecycle\.assistantSession\.approved_operation_indexes/);
assert.match(assistant, /Assistant 실행 실패/);
assert.match(assistant, /workflowError/);
assert.match(assistant, /요청 취소/);
assert.match(builderStyles, /\.report-assistant-cancel\{[^}]*align-self:flex-start/);
assert.match(builderStyles, /\.report-assistant-cancel\{[^}]*border-radius:14px/);
assert.match(assistant, /처리 중에는 취소할 수 없습니다/);
assert.match(page, /onCancel=\{lifecycle\.cancelAssistantSession\}/);
assert.match(controller, /submitAssistantInstruction/);
assert.match(controller, /approveAssistantRequest/);
assert.match(controller, /lifecycle\.approveAssistantPatch\(operationIndexes\)/);
assert.match(controller, /session\?\.phase !== "saving_revision"/);
assert.match(controller, /resumeAssistantRevision\(session\)/);
assert.match(controller, /artifacts\.loadArtifacts\(result\.definition, true\)/);
assert.match(controller, /answervice\.report-assistant:/);
assert.match(page, /approvalRequest=/);
assert.match(page, /workflowStatus=/);
assert.doesNotMatch(assistant, /데이터 재조회 0건|mock|fixture/i);
assert.match(normalization, /artifact_id: block\.artifactId/);
assert.doesNotMatch(normalization, /query_id: block\.queryId/);
assert.doesNotMatch(normalization, /locked|selectedBlockIds|snapshots|clipboard|zoom/);

console.log("frontend Report Builder V2 shell tests passed");
