import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

function source(relativePath) {
  return readFileSync(new URL(`../../${relativePath}`, import.meta.url), "utf8");
}

const app = source("app/frontend/src/App.jsx");
const appStyles = source("app/frontend/src/styles.css");
const flags = source("app/frontend/src/features/reports/reportBuilderFlags.js");
const controller = source("app/frontend/src/features/reports/useReportsPageController.jsx");
const page = source("app/frontend/src/pages/ReportsPage.jsx");
const toolbar = source("app/frontend/src/features/reports/components/ReportEditorToolbar.jsx");
const editorBlock = source("app/frontend/src/features/reports/components/ReportEditorBlock.jsx");
const markdownEditor = source("app/frontend/src/features/reports/components/MarkdownBlockEditor.jsx");
const toolPanel = source("app/frontend/src/features/reports/components/ReportToolPanel.jsx");
const properties = source("app/frontend/src/features/reports/components/ReportPropertiesPanel.jsx");
const assistant = source("app/frontend/src/features/reports/components/ReportAssistantPanel.jsx");
const builder = source("app/frontend/src/features/reports/v2/ReportBuilderV2.jsx");
const builderStyles = source("app/frontend/src/features/reports/v2/report-builder-v2.css");
const shortcutHelp = source("app/frontend/src/features/reports/v2/ReportShortcutHelp.jsx");
const presentation = source("app/frontend/src/features/reports/v2/ReportPresentation.jsx");
const canvas = source("app/frontend/src/features/reports/ReportPageCanvas.jsx");
const viewport = source("app/frontend/src/features/reports/reportEditorViewport.ts");
const normalization = source("app/frontend/src/contracts/reportNormalization.ts");

assert.match(flags, /VITE_REPORT_BUILDER_V2 !== "false"/);
assert.doesNotMatch(flags, /SHOWCASE/);
assert.doesNotMatch(app, /ReportAssistantShowcase|REPORT_ASSISTANT_SHOWCASE/);
assert.match(app, /reportEditorMode && REPORT_BUILDER_V2 \? "report-builder-v2-mode"/);
assert.match(app, /<ReportsPage[\s\S]*?theme=\{theme\}[\s\S]*?onToggleTheme=\{toggleTheme\}/);
assert.match(appStyles, /html:has\(\.report-builder-v2-mode\),body:has\(\.report-builder-v2-mode\)\{overflow:hidden\}/);
assert.match(appStyles, /\.report-builder-v2-mode\{position:fixed;inset:0;width:100%;height:100dvh;min-height:0;overflow:hidden\}/);
assert.doesNotMatch(controller, /REPORT_REVIEW_MODE|reviewDefinition|mockReport/i);
assert.match(page, /page\.builderV2 \? <ReportBuilderV2/);
assert.match(builder, /data-report-builder="v2"/);
assert.match(builder, /report-builder-v2-layout/);
assert.match(builder, /builder-library-column/);
assert.match(builder, /builder-workspace/);
assert.match(builder, /requestFullscreen/);
assert.match(builder, /pages\.map/);
assert.match(builder, /<ReportShortcutHelp/);
assert.match(builder, /\{presentation\}/);
assert.match(builder, /rightPanel === "assistant"/);
assert.match(builder, /className="builder-inspector"/);
assert.match(builderStyles, /\[data-report-builder="v2"\] \.report-builder-v2-layout/);
assert.match(builderStyles, /grid-template-columns:var\(--builder-library\) minmax\(620px,1fr\) var\(--builder-properties\)/);
assert.match(builderStyles, /\[data-report-builder="v2"\] \.report-properties-panel\{[^}]*display:block/);
assert.match(builderStyles, /@media\(max-width:1179px\)/);
assert.match(builderStyles, /@media\(max-width:900px\)/);
assert.match(builderStyles, /\.answer-report-canvas--editor\{padding:0/);
assert.match(builderStyles, /\.answer-report-page__block:has\(>\.selected\)/);
assert.match(builderStyles, /\.notion-block>\.report-block-chrome/);
assert.match(builderStyles, /\.report-shortcut-dialog/);
assert.match(builderStyles, /\.report-presentation/);
assert.doesNotMatch(builderStyles, /^\.notion-report-editor/m);
assert.match(canvas, /data-report-page-index=\{pageIndex\}/);
assert.match(canvas, /resolveReportEditorScale/);
assert.match(viewport, /fit-width/);
assert.match(viewport, /fit-page/);
assert.match(page, /draft\.addTemplateBlock\("artifact-chart", null, \{ chartType \}\)/);
assert.match(page, /onAddChart=\{addChartBlock\}/);
assert.match(page, /<ReportPresentation/);
assert.match(page, /renderBlock=\{page\.renderPreviewBlock\}/);
assert.match(page, /onToggleTheme=\{onToggleTheme\}/);
assert.match(page, /theme=\{theme\}/);
assert.match(shortcutHelp, /현재 보고서 저장/);
assert.match(shortcutHelp, /Ctrl \/ Cmd \+ Y/);
assert.match(shortcutHelp, /Alt \+ 휠/);
assert.match(shortcutHelp, /createPortal\(overlay, document\.body\)/);
assert.match(shortcutHelp, /editor\.inert = true/);
assert.match(shortcutHelp, /event\.key !== "Tab"/);
assert.doesNotMatch(shortcutHelp, /draft|서버에 저장|12열 격자/);
assert.doesNotMatch(shortcutHelp, /목업|Mock/);
assert.match(presentation, /createPortal\(overlay, document\.body\)/);
assert.match(presentation, /pageCountOverride=\{pageCount\}/);
assert.match(presentation, /overlayThemeClass = theme === "dark" \? "ppt-theme theme-dark" : "theme-light"/);
assert.doesNotMatch(presentation, /mock|월간 경영|호텔 매출/i);
assert.match(toolbar, /보고서 확대 축소/);
assert.match(toolbar, /<ThemeToggle className="report-editor-theme-toggle" theme=\{theme\} onToggle=\{onToggleTheme\}/);
assert.match(toolbar, />미리보기<\/button>/);
assert.doesNotMatch(toolbar, /"Preview"|HTML 초안/);
assert.match(toolbar, /\{!builderV2 && <span className="notion-status-chip">/);
assert.match(builderStyles, /\.editor-command-actions\{[^}]*flex-wrap:nowrap/);
assert.match(toolPanel, /report-template-grid/);
assert.match(builderStyles, /\.report-template-grid\{grid-template-columns:1fr\}/);
assert.match(builderStyles, /\.report-library-search\{margin:14px 14px 2px\}/);
assert.match(builderStyles, /\.editor-view-actions \.report-orientation-switch\{[^}]*box-shadow:none/);
assert.match(builderStyles, /\.report-orientation-switch button\[aria-pressed="true"\]\{[^}]*background:#eaf3ff!important/);
assert.match(builderStyles, /\.answer-report-page \.notion-markdown-input\{min-height:42px!important/);
assert.match(builderStyles, /\.answer-report-page \.report-markdown-toolbar\{min-height:32px/);
assert.match(builderStyles, /\.answer-report-page \.report-markdown-hint\{display:none\}/);
assert.match(markdownEditor, /onModeChange/);
assert.match(markdownEditor, /className="report-markdown-preview-actions"/);
assert.match(editorBlock, /const isBlockPreview =/);
assert.match(editorBlock, /is-block-preview/);
assert.match(builderStyles, /\.notion-block\.is-block-preview/);
assert.match(editorBlock, /resizeReportFrame/);
assert.match(editorBlock, /data-resize-direction=\{direction\}/);
assert.match(editorBlock, /\["n", "위쪽"\]/);
assert.match(editorBlock, /\["s", "아래쪽"\]/);
assert.match(builderStyles, /report-resize-handle--nw/);
assert.match(builderStyles, /report-resize-handle--se/);
assert.match(toolPanel, /<h2>블록 추가<\/h2>/);
assert.match(toolPanel, /추가할 블록 검색/);
assert.doesNotMatch(toolPanel, /보고서 구성|블록 라이브러리/);
assert.match(toolPanel, /REPORT_CHART_OPTIONS\.map/);
assert.match(builder, /className="builder-modal-scrim"/);
assert.match(builder, /inert=\{libraryModalOpen/);
assert.match(controller, /event\.key !== "Tab"/);
assert.match(properties, /const blockLocked =/);
assert.match(properties, /disabled=\{!canEdit \|\| blockLocked\}/);
assert.match(assistant, /onSubmit\(text\)/);
assert.match(page, /artifactTitle=\{page\.selectedArtifactSource\?\.title\}/);
assert.match(assistant, /artifactTitle \|\| "분석 결과를 선택해 주세요"/);
assert.match(assistant, /초안 반영 완료/);
assert.doesNotMatch(assistant, /trace\.model_version/);
assert.match(assistant, /request_user_approval|새 데이터 분석 승인 필요/);
assert.match(assistant, /onApproveDataRequest/);
assert.match(assistant, /저장 계속/);
assert.doesNotMatch(assistant, /REPORT ASSISTANT|보고서 AI Assistant|Revision 저장|Data Agent|새 Artifact/);
assert.match(assistant, /요청을 처리하지 못했습니다/);
assert.doesNotMatch(assistant, /workflowError|errorCode \?/);
assert.match(controller, /submitAssistantInstruction/);
assert.match(controller, /approveAssistantRequest/);
assert.match(controller, /artifacts\.loadArtifacts\(result\.definition, true\)/);
assert.match(controller, /if \(textField\) return;/);
assert.match(editorBlock, /addEventListener\("wheel", resizeTableWithWheel, \{ passive: false \}\)/);
assert.match(editorBlock, /removeEventListener\("wheel", resizeTableWithWheel\)/);
assert.match(controller, /answervice\.report-assistant:/);
assert.match(page, /approvalRequest=/);
assert.match(page, /workflowStatus=/);
assert.doesNotMatch(assistant, /데이터 재조회 0건|mock|fixture/i);
assert.match(normalization, /artifact_id: block\.artifactId/);
assert.match(normalization, /query_id: block\.queryId/);
assert.doesNotMatch(normalization, /locked|selectedBlockIds|snapshots|clipboard|zoom/);

console.log("frontend Report Builder V2 shell tests passed");
