import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

function source(relativePath) {
  return readFileSync(new URL(`../../${relativePath}`, import.meta.url), "utf8");
}

const app = source("app/frontend/src/App.jsx");
const appStyles = source("app/frontend/src/styles.css");
const flags = source("app/frontend/src/features/reports/reportBuilderFlags.js");
const controller = source("app/frontend/src/features/reports/useReportsPageController.jsx");
const page = source("app/frontend/src/pages/ReportsPage.jsx");
const toolbar = source("app/frontend/src/features/reports/components/ReportEditorToolbar.jsx");
const editorBlock = source("app/frontend/src/features/reports/components/ReportEditorBlock.jsx");
const blockControls = source("app/frontend/src/features/reports/components/ReportBlockControls.jsx");
const toolPanel = source("app/frontend/src/features/reports/components/ReportToolPanel.jsx");
const properties = source("app/frontend/src/features/reports/components/ReportPropertiesPanel.jsx");
const assistant = source("app/frontend/src/features/reports/components/ReportAssistantPanel.jsx");
const builder = source("app/frontend/src/features/reports/v2/ReportBuilderV2.jsx");
const builderStyles = source("app/frontend/src/features/reports/v2/report-builder-v2.css");
const shortcutHelp = source("app/frontend/src/features/reports/v2/ReportShortcutHelp.jsx");
const presentation = source("app/frontend/src/features/reports/v2/ReportPresentation.jsx");
const canvas = source("app/frontend/src/features/reports/ReportPageCanvas.jsx");
const viewport = source("app/frontend/src/features/reports/reportEditorViewport.ts");
const normalization = source("app/frontend/src/contracts/reportNormalization.ts");
const reportPresentation = source("app/frontend/src/features/reports/components/reportPresentation.js");
const draftOperations = source("app/frontend/src/features/reports/reportDraftOperations.js");

assert.match(flags, /VITE_REPORT_BUILDER_V2 !== "false"/);
assert.doesNotMatch(flags, /SHOWCASE/);
assert.doesNotMatch(app, /ReportAssistantShowcase|REPORT_ASSISTANT_SHOWCASE/);
assert.match(app, /reportEditorMode && REPORT_BUILDER_V2 \? "report-builder-v2-mode"/);
assert.match(app, /<ReportsPage[\s\S]*?theme=\{theme\}[\s\S]*?onToggleTheme=\{toggleTheme\}/);
assert.match(appStyles, /html:has\(\.report-builder-v2-mode\),body:has\(\.report-builder-v2-mode\)\{overflow:hidden\}/);
assert.match(appStyles, /\.report-builder-v2-mode\{position:fixed;inset:0;width:100%;height:100dvh;min-height:0;overflow:hidden\}/);
assert.match(appStyles, /\.report-builder-v2-mode>\.workspace\{height:100%;min-height:0;display:grid;grid-template-rows:minmax\(0,1fr\);overflow:hidden\}/);
assert.match(appStyles, /\.report-builder-v2-mode>\.workspace>\.page-stage\{height:auto;min-height:0;overflow:hidden;padding:0\}/);
assert.match(appStyles, /\.report-builder-v2-mode>\.workspace>\.topbar\{display:none\}/);
assert.doesNotMatch(controller, /REPORT_REVIEW_MODE|reviewDefinition|mockReport/i);
assert.match(page, /page\.builderV2 \? <ReportBuilderV2/);
assert.match(builder, /data-report-builder="v2"/);
assert.match(builder, /report-builder-v2-layout/);
assert.match(builder, /builder-library-column/);
assert.match(builder, /builder-workspace/);
assert.match(builder, /requestFullscreen/);
assert.match(builder, /pages\.map/);
assert.match(builder, /<ReportShortcutHelp/);
assert.match(builder, /\{presentation\}/);
assert.match(builder, /rightPanel === "assistant"/);
assert.match(builder, /className="builder-inspector"/);
assert.match(builderStyles, /\[data-report-builder="v2"\] \.report-builder-v2-layout/);
assert.match(builderStyles, /grid-template-columns:var\(--builder-library\) minmax\(620px,1fr\) var\(--builder-properties\)/);
assert.match(builderStyles, /\[data-report-builder="v2"\] \.report-properties-panel\{[^}]*display:block/);
assert.match(builderStyles, /@media\(max-width:1179px\)/);
assert.match(builderStyles, /@media\(max-width:900px\)/);
assert.match(builderStyles, /\.answer-report-canvas--editor\{padding:0/);
assert.match(builderStyles, /\.answer-report-page__block:has\(>\.selected\)/);
assert.match(builderStyles, /\.notion-block>\.report-block-chrome/);
assert.match(builderStyles, /\.report-shortcut-dialog/);
assert.match(builderStyles, /\.report-presentation/);
assert.doesNotMatch(builderStyles, /^\.notion-report-editor/m);
assert.match(canvas, /data-report-page-index=\{pageIndex\}/);
assert.match(canvas, /resolveReportEditorScale/);
assert.match(viewport, /fit-width/);
assert.match(viewport, /fit-page/);
assert.match(page, /draft\.addTemplateBlock\("artifact-chart", null, \{ chartType \}\)/);
assert.match(page, /onAddChart=\{addChartBlock\}/);
assert.match(page, /<ReportPresentation/);
assert.match(page, /renderBlock=\{page\.renderPreviewBlock\}/);
assert.match(page, /onToggleTheme=\{onToggleTheme\}/);
assert.match(page, /theme=\{theme\}/);
assert.match(shortcutHelp, /현재 draft를 서버에 저장/);
assert.match(shortcutHelp, /Ctrl \/ Cmd \+ Y/);
assert.match(shortcutHelp, /Alt \+ 휠/);
assert.doesNotMatch(shortcutHelp, /목업|Mock/);
assert.match(presentation, /overlayThemeClass = theme === "dark" \? "ppt-theme theme-dark" : "theme-light"/);
assert.match(shortcutHelp, /onKeyDown=\{\(event\) =>/);
assert.match(shortcutHelp, /event\.stopPropagation\(\)/);
assert.match(presentation, /createPortal\(overlay, document\.body\)/);
assert.match(presentation, /pageCountOverride=\{pageCount\}/);
assert.match(presentation, /event\.key === " " && event\.target\.closest\?\./);
assert.match(presentation, /onKeyDown=\{navigate\}/);
assert.match(presentation, /event\.stopPropagation\(\)/);
assert.match(presentation, /ref=\{triggerRef\}/);
assert.match(presentation, /triggerRef\.current\?\.focus\(\)/);
assert.doesNotMatch(presentation, /document\.addEventListener\("keydown"/);
assert.match(builder, /ref=\{shortcutTriggerRef\}/);
assert.doesNotMatch(presentation, /mock|월간 경영|호텔 매출/i);
assert.match(toolbar, /보고서 확대 축소/);
assert.match(toolbar, /<ThemeToggle className="report-editor-theme-toggle" theme=\{theme\} onToggle=\{onToggleTheme\}/);
assert.match(toolbar, /role="region" aria-label="편집 명령\. 작은 화면에서는 좌우로 스크롤할 수 있습니다\." tabIndex=\{0\}/);
assert.match(toolbar, /builderV2 \? "Preview" : "HTML 초안 확인"/);
assert.match(toolbar, /\{!builderV2 && <span className="notion-status-chip">/);
assert.match(builderStyles, /\.editor-command-actions\{[^}]*flex-wrap:nowrap/);
assert.match(toolPanel, /report-template-grid/);
assert.match(builderStyles, /\.report-template-grid\{grid-template-columns:1fr\}/);
assert.match(builderStyles, /\.report-insert-grid>\.report-template-tile\{grid-template-columns:1fr\}/);
assert.match(builderStyles, /\.report-template-add\{[^}]*grid-template-columns:15px minmax\(0,1fr\)/);
assert.doesNotMatch(builderStyles, /report-template-drag|report-template-grip/);
assert.match(builderStyles, /\.report-library-search\{margin:14px 14px 0\}/);
assert.match(builderStyles, /\.editor-view-actions \.report-orientation-switch\{[^}]*box-shadow:none/);
assert.match(builderStyles, /\.report-orientation-switch button\[aria-pressed="true"\]\{[^}]*background:#eaf3ff!important/);
assert.match(builderStyles, /\.answer-report-page \.notion-markdown-input\{min-height:42px!important/);
assert.match(builderStyles, /\.answer-report-page \.report-markdown-toolbar\{min-height:32px/);
assert.match(builderStyles, /\.answer-report-page \.report-markdown-hint\{display:none\}/);
assert.match(builderStyles, /\.theme-light \[data-report-builder="v2"\] \.notion-block \.report-drag-handle[^\n]*background:#f1f5fa/);
assert.match(builderStyles, /\.theme-light \[data-report-builder="v2"\] \.report-block-menu-popover\{[^}]*color:#29445f[^}]*background:#fff/);
assert.match(builderStyles, /\.theme-light \.report-template-overlay\{[^}]*color:#17324f[^}]*background:#fff/);
assert.match(builderStyles, /\.theme-light \[data-report-builder="v2"\] \.report-drop-preview\{[^}]*background:rgba\(226,239,255,\.9\)!important/);
assert.match(builderStyles, /\.theme-light \[data-report-builder="v2"\] \.report-slash-menu\{[^}]*color:#29445f[^}]*background:#fff/);
assert.match(builderStyles, /\.report-template-tile\[aria-disabled="true"\][^\n]*opacity:1/);
assert.match(builderStyles, /\.notion-editor-topbar button:disabled,[^\n]*opacity:1/);
assert.match(builderStyles, /\.report-library-search input::placeholder,[^\n]*opacity:1/);
assert.match(builderStyles, /\.theme-light \[data-report-builder="v2"\] \.report-library-search input::placeholder,[^\n]*color:#5f7288;opacity:1/);
assert.match(builderStyles, /\.report-presentation\.theme-light\{[^}]*background:#edf3f8/);
assert.match(builderStyles, /\.report-presentation\.theme-light>main\{[^}]*radial-gradient/);
assert.match(builderStyles, /\.report-api-state,[^\n]*overflow-wrap:anywhere/);
assert.match(builderStyles, /\.report-property-evidence code\{[^}]*white-space:normal[^}]*overflow-wrap:anywhere/);
assert.match(editorBlock, /aria-label=\{`\$\{block\.title\} 블록 이동`\}/);
assert.match(editorBlock, /const RESIZE_DIRECTIONS = \[/);
assert.match(editorBlock, /aria-label=\{`\$\{block\.title\} 블록 \$\{label\} 크기 조절`\}/);
assert.match(editorBlock, /RESIZE_DIRECTIONS\.map/);
assert.doesNotMatch(blockControls, /report-template-minimap/);
assert.doesNotMatch(builderStyles, /report-template-minimap/);
assert.match(properties, /unifySelectedSize\("width"\)/);
assert.match(properties, /unifySelectedSize\("height"\)/);
assert.match(page, /onSelectBlocks=\{page\.editorTools\.selectBlocks\}/);
assert.match(builderStyles, /\.report-marquee-selection/);
assert.match(editorBlock, /!event\.altKey \|\| event\.deltaY === 0 \|\| block\.type !== "table" \|\| !isDraft \|\| locked/);
assert.match(editorBlock, /const step = event\.deltaY < 0 \? 1 : -1/);
assert.match(editorBlock, /addEventListener\("wheel", resizeTableWithWheel, \{ passive: false \}\)/);
assert.match(editorBlock, /ref=\{setBlockNodeRef\}/);
assert.match(blockControls, /aria-label=\{`\$\{block\.title\} 블록 메뉴`\}/);
assert.match(builderStyles, /@media\(max-width:1179px\)\{[\s\S]*grid-template-columns:minmax\(0,1fr\)/);
assert.match(builderStyles, /width:min\(320px,calc\(100vw - 64px\)\)/);
assert.match(builderStyles, /@media\(max-width:1179px\)\{[\s\S]*\.builder-inspector-dismiss\{[^}]*display:grid/);
assert.match(builderStyles, /@media\(hover:none\)\{[\s\S]*\.report-block-chrome[^}]*opacity:1/);
assert.match(builder, /window\.matchMedia\("\(min-width: 1180px\)"\)\.matches/);
assert.match(toolPanel, /REPORT ELEMENTS/);
assert.match(toolPanel, /보고서 블록 검색/);
assert.match(toolPanel, /REPORT_CHART_OPTIONS\.map/);
assert.match(properties, /const blockLocked =/);
assert.match(properties, /disabled=\{!canEdit \|\| blockLocked\}/);
assert.match(assistant, /onSubmit\(text\)/);
assert.match(page, /artifactTitle=\{page\.selectedArtifactSource\?\.title\}/);
assert.match(page, /artifactOptions=\{artifacts\.assistantArtifactOptions\}/);
assert.match(assistant, /artifactTitle \|\| "분석 Artifact를 선택해 주세요"/);
assert.match(assistant, /artifactOptions\.length > 1/);
assert.match(assistant, /근거 변경/);
assert.match(assistant, /evidencePickerOpen && <dialog/);
assert.match(assistant, /className="report-assistant-evidence-picker"/);
assert.match(assistant, /className="report-assistant-evidence-options"/);
assert.match(assistant, /title=\{option\.title \|\| "승인 Artifact"\}/);
assert.match(assistant, /draftArtifactIds\.length >= 5/);
assert.match(assistant, /대표 근거 · 필수/);
assert.match(assistant, /onSelectArtifacts\(draftArtifactIds\)/);
assert.match(assistant, /선택한 근거만 검증해 Assistant에 전달합니다/);
assert.doesNotMatch(assistant, /<fieldset className="report-assistant-context"/);
assert.match(builderStyles, /\.report-assistant-evidence-options\{[^}]*display:grid;grid-template-columns:minmax\(0,1fr\)/);
assert.match(builderStyles, /\.report-assistant-evidence-options label\{[^}]*min-width:0;[^}]*grid-template-columns:auto minmax\(0,1fr\)/);
assert.match(builderStyles, /\.report-assistant-evidence-options span,\[data-report-builder="v2"\] \.report-assistant-evidence-options b\{[^}]*min-width:0;overflow-wrap:anywhere/);
assert.match(builderStyles, /\.report-assistant-panel\{[^}]*grid-template-columns:minmax\(0,1fr\)/);
assert.match(builderStyles, /\.report-assistant-evidence-picker\{[^}]*width:min\(440px,calc\(100vw - 32px\)\);[^}]*max-height:min\(620px,calc\(100dvh - 48px\)\)/);
assert.match(builderStyles, /\.report-assistant-evidence-picker>\.report-assistant-evidence-options\{[^}]*overflow-x:hidden;overflow-y:auto/);
assert.match(builderStyles, /\.theme-light \[data-report-builder="v2"\] \.report-assistant-evidence-picker/);
assert.match(assistant, /AI 초안 반영 완료/);
assert.match(assistant, /trace\.model_version/);
assert.match(assistant, /request_user_approval|새 데이터 분석 승인 필요/);
assert.match(assistant, /onApproveDataRequest/);
assert.match(assistant, /Revision 저장 재개/);
assert.match(assistant, /report-assistant-patch-items/);
assert.match(assistant, /selectedIndexes/);
assert.match(assistant, /onApprove\(selectedIndexes\)/);
assert.match(assistant, /useId\(\)/);
assert.match(assistant, /htmlFor=\{inputId\}/);
assert.match(assistant, /전체 선택/);
assert.match(assistant, /전체 해제/);
assert.match(assistant, /개 선택/);
assert.match(assistant, /<details className="report-assistant-patch-detail">/);
assert.match(assistant, /내용 펼치기/);
assert.match(assistant, /approvalRef\.current\?\.focus\(\)/);
assert.match(assistant, /PATCH_IMPACT_LABEL/);
assert.match(assistant, /set_currency_display_unit: "통화 표시 단위 변경"/);
assert.match(assistant, /compact_report_layout: "전체 레이아웃 정리"/);
assert.match(assistant, /add_report_page: "빈 페이지 추가"/);
assert.match(assistant, /update_block_title: "블록 제목 변경"/);
assert.match(assistant, /resize_block: "블록 크기 변경"/);
assert.match(assistant, /update_chart_settings: "차트 설정 변경"/);
assert.match(assistant, /update_table_settings: "표 설정 변경"/);
assert.match(assistant, /선택한 변경 영향/);
assert.match(assistant, /preview\.items\.filter\(\(item\) => selectedIndexes\.includes\(item\.index\)\)/);
assert.match(assistant, /evidenceRequired/);
assert.match(assistant, /impactCategories\.includes\("DESTRUCTIVE"\)/);
assert.match(assistant, /새 Revision으로 저장되어 이전 버전을 유지합니다/);
assert.match(builderStyles, /:focus-visible/);
assert.match(builderStyles, /@media\(prefers-reduced-motion:reduce\)/);
assert.match(builderStyles, /@media\(max-width:480px\)/);
assert.match(builderStyles, /grid-template-columns:repeat\(auto-fit/);
assert.match(page, /approvedIndexes: lifecycle\.assistantSession\.approved_operation_indexes/);
assert.match(assistant, /Assistant 실행 실패/);
assert.match(assistant, /workflowError/);
assert.match(assistant, /요청 취소/);
assert.match(builderStyles, /\.report-assistant-cancel\{[^}]*align-self:flex-start/);
assert.match(builderStyles, /\.report-assistant-cancel\{[^}]*border-radius:14px/);
assert.match(assistant, /처리 중에는 취소할 수 없습니다/);
assert.match(page, /onCancel=\{lifecycle\.cancelAssistantSession\}/);
assert.match(controller, /submitAssistantInstruction/);
assert.match(controller, /approveAssistantRequest/);
assert.match(controller, /lifecycle\.approveAssistantPatch\(operationIndexes\)/);
assert.match(controller, /session\?\.phase !== "saving_revision"/);
assert.match(controller, /resumeAssistantRevision\(session\)/);
assert.match(controller, /artifacts\.loadArtifacts\(result\.definition, true\)/);
assert.match(controller, /if \(textField\) return;/);
assert.match(editorBlock, /addEventListener\("wheel", resizeTableWithWheel, \{ passive: false \}\)/);
assert.match(editorBlock, /removeEventListener\("wheel", resizeTableWithWheel\)/);
assert.match(controller, /answervice\.report-assistant:/);
assert.match(page, /approvalRequest=/);
assert.match(page, /workflowStatus=/);
assert.doesNotMatch(assistant, /데이터 재조회 0건|mock|fixture/i);
assert.match(normalization, /artifact_id: block\.artifactId/);
assert.doesNotMatch(normalization, /query_id: block\.queryId/);
assert.doesNotMatch(normalization, /locked|selectedBlockIds|snapshots|clipboard|zoom/);
assert.match(reportPresentation, /block\.type === "page_break"/);
assert.match(reportPresentation, /startPage\(row\.sourceY \+ 1\)/);
assert.match(draftOperations, /kind: "pageBreak"/);
assert.match(draftOperations, /block\.kind === "pageBreak"/);

console.log("frontend Report Builder V2 shell tests passed");
