connector.name=clickhouse
connection-url=jdbc:clickhouse://facility-clickhouse:8123/
connection-user=${ENV:FACILITY_READONLY_USER}
connection-password=${ENV:FACILITY_READONLY_PASSWORD}
clickhouse.map-string-as-varchar=true
unsupported-type-handling=CONVERT_TO_VARCHAR
