#!/usr/bin/env sh
set -eu

clickhouse-client \
  --user "$CLICKHOUSE_USER" \
  --password "$CLICKHOUSE_PASSWORD" \
  --multiquery <<SQL
CREATE USER IF NOT EXISTS ${FACILITY_READONLY_USER}
IDENTIFIED WITH sha256_password BY '${FACILITY_READONLY_PASSWORD}';
ALTER USER ${FACILITY_READONLY_USER}
IDENTIFIED WITH sha256_password BY '${FACILITY_READONLY_PASSWORD}';
GRANT facility_readonly TO ${FACILITY_READONLY_USER};
SET DEFAULT ROLE facility_readonly TO ${FACILITY_READONLY_USER};
ALTER USER ${FACILITY_READONLY_USER} SETTINGS readonly=1;
SQL
