# Generated by Django 5.1.15 on 2026-07-27 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senseplace', '0001_dsg_v2_16_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factvoc',
            name='voc_id',
            field=models.CharField(help_text='VOC 고유 ID', max_length=64, primary_key=True, serialize=False),
        ),
    ]
