# Generated by Django 5.1.15 on 2026-07-29 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senseplace', '0002_alter_factvoc_voc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='author_name',
            field=models.CharField(blank=True, default='', help_text='작성자 이름', max_length=64),
        ),
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('WEEKLY', '주간'), ('MONTHLY', '월간'), ('QUARTERLY', '분기')], default='WEEKLY', help_text='보고서 유형 (주간/월간/분기)', max_length=16),
        ),
    ]
