# Generated by Django 5.1.15 on 2026-07-29 01:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senseplace', '0003_report_author_name_report_report_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('data_source_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='데이터 소스 ID', primary_key=True, serialize=False)),
                ('source_code', models.CharField(help_text='소스 코드 (PMS/POS/CRM/FACILITY/BANQUET)', max_length=32)),
                ('source_name', models.CharField(help_text='관리자 표시명', max_length=120)),
                ('engine_type', models.CharField(choices=[('POSTGRESQL', 'PostgreSQL'), ('MYSQL', 'MySQL'), ('SQLSERVER', 'SQL Server'), ('CLICKHOUSE', 'ClickHouse')], help_text='엔진 (POSTGRESQL/MYSQL/SQLSERVER/CLICKHOUSE)', max_length=24)),
                ('platform_instance', models.CharField(help_text='DataHub platform instance', max_length=128)),
                ('trino_catalog', models.CharField(help_text='Trino catalog', max_length=128)),
                ('datahub_recipe_ref', models.CharField(help_text='버전 고정 recipe 경로', max_length=255)),
                ('connection_ref', models.CharField(help_text='credential 참조 (env 또는 Secret Manager)', max_length=255)),
                ('owner_team', models.CharField(help_text='담당 조직', max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ERROR', 'Error'), ('DISABLED', 'Disabled')], default='ACTIVE', help_text='연결 상태 (DRAFT/ACTIVE/ERROR/DISABLED)', max_length=16)),
                ('last_health_status', models.CharField(blank=True, choices=[('HEALTHY', 'Healthy'), ('DEGRADED', 'Degraded'), ('DOWN', 'Down'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', help_text='최근 health (HEALTHY/DEGRADED/DOWN/UNKNOWN)', max_length=16)),
                ('last_health_at', models.DateTimeField(blank=True, help_text='최근 점검 시각 (UTC)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 시각 (UTC)')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 시각 (UTC)')),
            ],
            options={
                'verbose_name': 'Data Source',
                'verbose_name_plural': 'Data Sources',
                'db_table': 'data_sources',
            },
        ),
    ]
