# Generated by Django 5.1.15 on 2026-07-29 01:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senseplace', '0004_datasource'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProduct',
            fields=[
                ('data_product_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='데이터 제품 ID', primary_key=True, serialize=False)),
                ('product_name', models.CharField(help_text='제품명 (예: Reservation Fact)', max_length=160)),
                ('source_name', models.CharField(help_text='원천 소스명', max_length=120)),
                ('catalog_ref', models.CharField(help_text='catalog 참조 (예: pms.reservation)', max_length=128)),
                ('domain', models.CharField(help_text='업무 도메인', max_length=64)),
                ('owner_team', models.CharField(help_text='담당 조직', max_length=100)),
                ('freshness_label', models.CharField(help_text='최신성 라벨 (예: 1분)', max_length=32)),
                ('quality_score', models.PositiveIntegerField(default=0, help_text='품질 점수 (0~100)')),
                ('sensitivity', models.CharField(choices=[('INTERNAL', 'Internal'), ('RESTRICTED', 'Restricted'), ('CONFIDENTIAL', 'Confidential')], default='INTERNAL', help_text='민감도 (Internal/Restricted/Confidential)', max_length=16)),
                ('tool_name', models.CharField(help_text='사용 Tool명', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 시각 (UTC)')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 시각 (UTC)')),
            ],
            options={
                'verbose_name': 'Data Product',
                'verbose_name_plural': 'Data Products',
                'db_table': 'data_products',
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('tool_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Tool ID', primary_key=True, serialize=False)),
                ('tool_code', models.CharField(help_text='안정 호출 키', max_length=96)),
                ('tool_type', models.CharField(choices=[('SQL', 'Data'), ('DATAHUB', 'Metadata'), ('RAG', 'Knowledge'), ('ML', 'ML · ONNX')], help_text='Tool 유형 (SQL/DATAHUB/RAG/ML)', max_length=16)),
                ('semantic_version', models.CharField(help_text='semantic version', max_length=32)),
                ('name', models.CharField(help_text='Tool 명', max_length=160)),
                ('description', models.TextField(blank=True, default='', help_text='설명')),
                ('input_schema_json', models.JSONField(default=dict, help_text='입력 schema')),
                ('output_schema_json', models.JSONField(default=dict, help_text='출력 schema')),
                ('transport', models.CharField(choices=[('INTERNAL', 'Internal'), ('HTTP', 'HTTP'), ('MCP_STDIO', 'MCP stdio'), ('MCP_SSE', 'MCP sse')], default='INTERNAL', help_text='transport (INTERNAL/HTTP/MCP_STDIO/MCP_SSE)', max_length=24)),
                ('endpoint_ref', models.CharField(blank=True, default='', help_text='endpoint 참조 (secret 원문 금지)', max_length=255)),
                ('timeout_seconds', models.PositiveIntegerField(default=30, help_text='timeout')),
                ('required_roles_json', models.JSONField(default=list, help_text='필수 역할')),
                ('tool_hints_json', models.JSONField(default=dict, help_text='Tool hints (readOnly/destructive/idempotent)')),
                ('is_enabled', models.BooleanField(default=False, help_text='활성 여부 (P2 전 false)')),
                ('health_status', models.CharField(choices=[('HEALTHY', 'Healthy'), ('DEGRADED', 'Degraded'), ('DOWN', 'Down'), ('UNKNOWN', 'Unknown')], default='HEALTHY', help_text='health (HEALTHY/DEGRADED/DOWN/UNKNOWN)', max_length=16)),
                ('success_rate', models.FloatField(blank=True, help_text='최근 성공률 (예: 98.7)', null=True)),
                ('last_run_at', models.DateTimeField(blank=True, help_text='최근 실행 시각 (UTC)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 시각 (UTC)')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 시각 (UTC)')),
            ],
            options={
                'verbose_name': 'Tool',
                'verbose_name_plural': 'Tools',
                'db_table': 'tool_registry',
            },
        ),
    ]
