# Generated by Django 5.1.15 on 2026-07-29 01:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senseplace', '0005_dataproduct_tool'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentWorkflowStep',
            fields=[
                ('step_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='단계 ID', primary_key=True, serialize=False)),
                ('step_order', models.PositiveIntegerField(help_text='실행 순서 (1부터)')),
                ('step_name', models.CharField(help_text='단계명 (예: 질문 해석)', max_length=64)),
                ('status', models.CharField(choices=[('COMPLETED', '완료'), ('IN_PROGRESS', '진행 중'), ('PENDING', '대기')], default='COMPLETED', help_text='단계 상태', max_length=16)),
                ('description', models.TextField(blank=True, default='', help_text='단계 설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 시각 (UTC)')),
            ],
            options={
                'verbose_name': 'Agent Workflow Step',
                'verbose_name_plural': 'Agent Workflow Steps',
                'db_table': 'agent_workflow_step',
                'ordering': ['step_order'],
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('customer_id', models.CharField(help_text='마스킹된 고객 ID (예: CUS-84••12)', max_length=32, primary_key=True, serialize=False)),
                ('display_name', models.CharField(help_text='마스킹된 표시명 (예: 김*현)', max_length=32)),
                ('member_no', models.CharField(blank=True, default='', help_text='CRM 회원 번호 참조', max_length=36)),
                ('tier_label', models.CharField(help_text='등급 라벨 (예: VIP Gold)', max_length=32)),
                ('stays_count', models.PositiveIntegerField(default=0, help_text='총 투숙 횟수')),
                ('revenue_display', models.CharField(help_text='누적 매출 표시 (예: ₩5,760,000)', max_length=32)),
                ('revisit_score', models.PositiveIntegerField(default=0, help_text='재방문 예측 점수 (0~100)')),
                ('sentiment_label', models.CharField(help_text='감성 라벨 (긍정/중립/부정)', max_length=16)),
                ('last_issue', models.CharField(blank=True, default='', help_text='최근 이슈', max_length=64)),
                ('last_stay_date', models.CharField(help_text='최근 투숙일 (예: 2026.07.18)', max_length=16)),
                ('preferred_room', models.CharField(help_text='선호 객실', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 시각 (UTC)')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 시각 (UTC)')),
            ],
            options={
                'verbose_name': 'Customer Profile',
                'verbose_name_plural': 'Customer Profiles',
                'db_table': 'customer_profile',
            },
        ),
    ]
