CREATE OR REPLACE VIEW facility_reference_codes AS
SELECT 'FACILITY_TYPE' AS category, arrayJoin([
    'SPA', 'POOL', 'FITNESS', 'ACTIVITY', 'MEETING_SUPPORT', 'BACK_OF_HOUSE'
]) AS code
UNION ALL
SELECT 'EVENT_TYPE', arrayJoin(['USAGE', 'INSPECTION', 'INCIDENT'])
UNION ALL
SELECT 'DATA_PERIOD_STATUS', arrayJoin([
    'REFERENCE_CALIBRATED', 'SYNTHETIC_ACTUAL_LIKE',
    'YTD_SYNTHETIC', 'FORECAST_SCENARIO'
]);
