#!/usr/bin/env sh
set -eu
clickhouse-client --user "$CLICKHOUSE_USER" --password "$CLICKHOUSE_PASSWORD" --multiquery <<SQL
CREATE USER IF NOT EXISTS $FACILITY_RO_USERNAME IDENTIFIED WITH sha256_password BY '$FACILITY_RO_PASSWORD';
GRANT SELECT ON $CLICKHOUSE_DB.* TO $FACILITY_RO_USERNAME;
SQL
