source:
  type: postgres
  config:
    host_port: banquet-postgres:5432
    database: ${BANQUET_DB_NAME}
    username: ${BANQUET_READONLY_USER}
    password: ${BANQUET_READONLY_PASSWORD}
    platform_instance: banquet_v4
    schema_pattern:
      allow: [walkerhill_v4]
sink:
  type: datahub-rest
  config:
    server: http://datahub-gms-quickstart:8080
