source:
  type: postgres
  config:
    host_port: banquet-postgres:5432
    database: ${BANQUET_DB_NAME}
    username: ${BANQUET_READONLY_USER}
    password: ${BANQUET_READONLY_PASSWORD}
    platform_instance: banquet
    schema_pattern:
      allow:
        - public
sink:
  type: datahub-rest
  config:
    server: http://datahub-gms-quickstart:8080
transformers:
  - type: simple_add_ownership
    config:
      owner_urns: ["urn:li:corpuser:banquet_sales"]
      entity_types: ["dataset"]
