source:
  type: mssql
  config:
    host_port: crm-mssql:1433
    database: ${CRM_DB_NAME}
    username: ${CRM_READONLY_USER}
    password: ${CRM_READONLY_PASSWORD}
    platform_instance: crm
    include_jobs: false
    schema_pattern:
      allow:
        - dbo
sink:
  type: datahub-rest
  config:
    server: http://datahub-gms-quickstart:8080
