source:
  type: clickhouse
  config:
    host_port: facility-clickhouse:8123
    database: walkerhill_v4
    username: ${FACILITY_READONLY_USER}
    password: ${FACILITY_READONLY_PASSWORD}
    platform_instance: facility_v4
sink:
  type: datahub-rest
  config:
    server: http://datahub-gms-quickstart:8080
