source:
  type: postgres
  config:
    host_port: pms-postgres:5432
    database: ${PMS_DB_NAME}
    username: ${PMS_READONLY_USER}
    password: ${PMS_READONLY_PASSWORD}
    platform_instance: pms
    schema_pattern:
      allow:
        - public
sink:
  type: datahub-rest
  config:
    server: http://datahub-gms-quickstart:8080
    token: ${DATAHUB_INGESTION_TOKEN}
transformers:
  - type: simple_add_dataset_domain
    config:
      domains: ["urn:li:domain:rooms"]
  - type: simple_add_dataset_tags
    config:
      tag_urns: ["urn:li:tag:AI_SEARCH_ALLOWED"]
  - type: simple_add_ownership
    config:
      owner_urns: ["urn:li:corpuser:hotel_operations"]
      entity_types: ["dataset"]
