source:
  type: mysql
  config:
    host_port: pos-mysql:3306
    database: ${POS_DB_NAME}
    username: ${POS_READONLY_USER}
    password: ${POS_READONLY_PASSWORD}
    platform_instance: pos
sink:
  type: datahub-rest
  config:
    server: http://datahub-gms-quickstart:8080
    token: ${DATAHUB_TOKEN}
