source:
  type: mysql
  config:
    host_port: pos-mysql:3306
    database: ${POS_DB_NAME}
    username: ${POS_READONLY_USER}
    password: ${POS_READONLY_PASSWORD}
    platform_instance: pos
sink:
  type: datahub-rest
  config:
    server: http://datahub-gms-quickstart:8080
    token: ${DATAHUB_INGESTION_TOKEN}
transformers:
  - type: simple_add_dataset_domain
    config:
      domains: ["urn:li:domain:food_and_beverage"]
  - type: simple_add_dataset_tags
    config:
      tag_urns: ["urn:li:tag:AI_SEARCH_ALLOWED"]
  - type: simple_add_ownership
    config:
      owner_urns: ["urn:li:corpuser:food_and_beverage_operations"]
      entity_types: ["dataset"]
