source:
  type: trino
  config:
    host_port: trino:8080
    database: serving
    username: datahub_ingestion
    env: PROD
    include_tables: false
    include_views: true
    include_view_lineage: true
    include_view_column_lineage: true
    ingest_lineage_to_connectors: false
    schema_pattern:
      allow:
        - analytics
    view_pattern:
      allow:
        - 'serving\.analytics\.banquet_monthly_metrics'
        - 'serving\.analytics\.facility_daily_metrics'
        - 'serving\.analytics\.fnb_daypart_metrics'
        - 'serving\.analytics\.hotel_daily_metrics'
        - 'serving\.analytics\.hotel_monthly_metrics'
        - 'serving\.analytics\.hotel_yearly_metrics'
        - 'serving\.analytics\.resource_monthly_metrics'
        - 'serving\.analytics\.workforce_monthly_metrics'
sink:
  type: datahub-rest
  config:
    server: http://datahub-gms-quickstart:8080
