connector.name=postgresql
connection-url=jdbc:postgresql://banquet-postgres:5432/hotel_banquet
connection-user=banquet_trino
connection-password=${ENV:BANQUET_TRINO_PASSWORD}
postgresql.include-system-tables=false
metadata.cache-ttl=1m
