connector.name=sqlserver
connection-url=jdbc:sqlserver://crm-mssql:1433;databaseName=hotel_crm;encrypt=true;trustServerCertificate=true
connection-user=crm_trino
connection-password=${ENV:CRM_TRINO_PASSWORD}
metadata.cache-ttl=1m
