connector.name=clickhouse
connection-url=jdbc:clickhouse://facility-clickhouse:8123/hotel_facility
connection-user=facility_trino
connection-password=${ENV:FACILITY_TRINO_PASSWORD}
metadata.cache-ttl=1m
