connector.name=postgresql
connection-url=jdbc:postgresql://pms-postgres:5432/hotel_pms
connection-user=pms_trino
connection-password=${ENV:PMS_TRINO_PASSWORD}
postgresql.include-system-tables=false
metadata.cache-ttl=1m
