USE [master];
GO

IF SUSER_ID(N'$(CRM_READONLY_USER)') IS NULL
    EXEC(N'CREATE LOGIN [$(CRM_READONLY_USER)] WITH PASSWORD = ''$(CRM_READONLY_PASSWORD)'', CHECK_POLICY = ON');
ELSE
    EXEC(N'ALTER LOGIN [$(CRM_READONLY_USER)] WITH PASSWORD = ''$(CRM_READONLY_PASSWORD)'', CHECK_POLICY = ON');
GO

USE [$(CRM_DB_NAME)];
GO

IF DATABASE_PRINCIPAL_ID(N'$(CRM_READONLY_USER)') IS NULL
    EXEC(N'CREATE USER [$(CRM_READONLY_USER)] FOR LOGIN [$(CRM_READONLY_USER)]');
GO

GRANT CONNECT TO [$(CRM_READONLY_USER)];
GRANT SELECT ON SCHEMA::crm TO [$(CRM_READONLY_USER)];
GRANT VIEW DEFINITION TO [$(CRM_READONLY_USER)];
DENY INSERT, UPDATE, DELETE, EXECUTE ON SCHEMA::crm TO [$(CRM_READONLY_USER)];
REVOKE CONTROL ON SCHEMA::crm FROM [$(CRM_READONLY_USER)];
DENY ALTER ON SCHEMA::crm TO [$(CRM_READONLY_USER)];
GO
