-- Conversation DDL의 단독 실행을 막고 immutable Alembic chain만 schema authority로 유지한다.
-- RETIRED: this file is preserved only as a compatibility breadcrumb.
--
-- Conversation schema ownership moved to the immutable Alembic chain at
-- revision 20260822_30. Do not execute standalone Conversation DDL: doing so
-- would create a second schema authority without migration, rollback, receipt,
-- or recovery guarantees.
--
-- Apply through:
--   app/backend/alembic.ini -> 20260822_30_conversation_safety_foundation.py
