-- service-demo-v3 PMS: deterministic seed 290613; [2025-01-01,2026-08-01)
SET client_encoding = 'UTF8';
SET timezone = 'Asia/Seoul';
BEGIN;
INSERT INTO seed_metadata(seed,data_class) VALUES (290613,'SYNTHETIC') ON CONFLICT (seed) DO UPDATE SET data_class=EXCLUDED.data_class;
WITH s AS (SELECT g, lpad(g::text,8,'0') AS k FROM generate_series(1,16000) g)
INSERT INTO pms_guests(property_id,guest_id,guest_segment,country_group,crm_mapping_eligible,is_synthetic,created_at,source_updated_at)
SELECT 'SYNTHETIC_HOTEL_001','PG-'||k, CASE WHEN g%11=0 THEN 'GROUP' WHEN g%5=0 THEN 'BUSINESS' ELSE 'LEISURE' END, CASE WHEN g%7=0 THEN 'OVERSEAS' ELSE 'DOMESTIC' END, CASE WHEN g<=11475 THEN true ELSE false END,true,timestamptz '2025-01-01 00:00:00+09',timestamptz '2026-08-01 00:00:00+09' FROM s;
WITH room_types(room_index,room_type_code,physical_rooms) AS (VALUES (0,'STANDARD',180),(1,'DELUXE',80),(2,'SUITE',30),(3,'RESIDENCE',10))
INSERT INTO pms_room_inventory_daily(property_id,inventory_id,business_date,room_type_code,physical_rooms,out_of_order_rooms,house_use_rooms,available_room_nights,data_period_status,is_forecast,is_synthetic,source_updated_at)
SELECT 'SYNTHETIC_HOTEL_001',day*4+room_index+1,date '2025-01-01'+day,room_type_code,physical_rooms,((day+room_index)%29=0)::int,((day+room_index)%53=0)::int,physical_rooms-((day+room_index)%29=0)::int-((day+room_index)%53=0)::int,'SYNTHETIC_ACTUAL_LIKE',false,true,timestamptz '2026-08-01 00:00:00+09'
FROM generate_series(0,576) day CROSS JOIN room_types;
WITH s AS (SELECT g FROM generate_series(1,43200) g), b AS (SELECT g, date '2025-01-01' + (((g*37+g::bigint*g*3)%573)::int) AS ci, CASE WHEN g<=37800 THEN 'CHECKED_OUT' WHEN g%23=0 THEN 'CANCELLED' WHEN g%29=0 THEN 'NO_SHOW' WHEN g%7=0 THEN 'CHECKED_IN' ELSE 'BOOKED' END AS st FROM s)
INSERT INTO pms_reservations(property_id,reservation_id,guest_id,booked_at,checkin_date,checkout_date,room_type_code,rate_plan_code,market_segment,booking_channel,reservation_status,adult_count,child_count,quoted_room_rate,gross_room_amount,booked_amount,discount_amount,commission_amount,refund_amount,cancellation_fee,cancelled_at,is_synthetic,data_period_status,is_forecast,source_updated_at)
SELECT 'SYNTHETIC_HOTEL_001','PR-'||lpad(g::text,8,'0'),'PG-'||lpad((((g*7919)%16000)+1)::text,8,'0'),(ci-((g%120)+1))::timestamp AT TIME ZONE 'Asia/Seoul',ci,ci+(1+g%4),CASE WHEN g%13=0 THEN 'SUITE' WHEN g%5=0 THEN 'DELUXE' ELSE 'STANDARD' END,CASE WHEN g%7=0 THEN 'CORPORATE' WHEN g%5=0 THEN 'GROUP' ELSE 'RACK' END,CASE WHEN g%7=0 THEN 'BUSINESS' WHEN g%5=0 THEN 'GROUP' ELSE 'LEISURE' END,CASE WHEN g%7=0 THEN 'CORPORATE' WHEN g%5=0 THEN 'OTA' ELSE 'DIRECT' END,st,1+g%3,g%2,120000+(g%9)*15000,(120000+(g%9)*15000)*(1+g%4),(120000+(g%9)*15000)*(1+g%4)-(CASE WHEN g%8=0 THEN 10000 ELSE 0 END),CASE WHEN g%8=0 THEN 10000 ELSE 0 END,CASE WHEN g%6=0 THEN 12000 ELSE 0 END,CASE WHEN st='CANCELLED' THEN 50000 ELSE 0 END,CASE WHEN st='CANCELLED' THEN (120000+(g%9)*15000)*(1+g%4)-(CASE WHEN g%8=0 THEN 10000 ELSE 0 END)-50000 ELSE 0 END,CASE WHEN st='CANCELLED' THEN (ci-2)::timestamp AT TIME ZONE 'Asia/Seoul' END,true,'SYNTHETIC_ACTUAL_LIKE',false,timestamptz '2026-08-01 00:00:00+09' FROM b;
WITH r AS (SELECT reservation_id,guest_id,checkin_date,checkout_date,room_type_code,reservation_status,adult_count,child_count FROM pms_reservations WHERE reservation_status='CHECKED_OUT' ORDER BY reservation_id LIMIT 37800)
INSERT INTO pms_stays(property_id,stay_id,reservation_id,guest_id,room_unit_code,actual_checkin_at,actual_checkout_at,stay_status,room_revenue,other_room_charges,complimentary_flag,house_use_flag,is_synthetic,data_period_status,is_forecast,source_updated_at,room_type_code,occupied_room_nights,guest_count)
SELECT 'SYNTHETIC_HOTEL_001','PS-'||substring(reservation_id from 4),reservation_id,guest_id,'R'||lpad((((row_number() over())%2308)+1)::text,4,'0'),(checkin_date::timestamp+interval '15 hours') AT TIME ZONE 'Asia/Seoul',(checkout_date::timestamp+interval '11 hours') AT TIME ZONE 'Asia/Seoul','COMPLETED',(checkout_date-checkin_date)*150000,CASE WHEN right(reservation_id,3)::integer%997=0 THEN 1 ELSE 0 END,false,false,true,'SYNTHETIC_ACTUAL_LIKE',false,timestamptz '2026-08-01 00:00:00+09',room_type_code,CASE WHEN reservation_status IN ('CHECKED_OUT','CHECKED_IN') THEN (checkout_date-checkin_date) ELSE 0 END,(adult_count+child_count) FROM r;
COMMIT;
