SET client_encoding = 'UTF8';
SET timezone = 'Asia/Seoul';
INSERT INTO seed_metadata(seed,data_class) VALUES(290613,'SYNTHETIC') ON CONFLICT(seed) DO UPDATE SET data_class=EXCLUDED.data_class;
WITH s AS (SELECT n,date '2025-01-01'+((n*37+n*n*3)%577) ed,CASE WHEN n%19=0 THEN 'CANCELLED' WHEN n%11=0 THEN 'INQUIRY' WHEN n%7=0 THEN 'QUOTED' WHEN n%5=0 THEN 'CONFIRMED' ELSE 'COMPLETED' END st FROM generate_series(1,2400) n)
INSERT INTO banquet_bookings(property_id,banquet_event_id,customer_id,inquiry_at,quoted_at,confirmed_at,cancelled_at,event_date,product_code,product_category,contracted_amount,cancellation_fee,expected_guests,actual_attendees,lead_source,sales_owner_team,booking_status,group_checkin_date,group_checkout_date,expected_room_nights,reserved_room_block_count,pickup_room_count,released_room_count,data_period_status,is_forecast,is_synthetic,source_updated_at)
SELECT 'SYNTHETIC_HOTEL_001','BE-'||lpad(n::text,8,'0'),'BC-'||lpad((((n*7919)%11475)+1)::text,8,'0'),(ed-((n%180)+14))::timestamp AT TIME ZONE 'Asia/Seoul',CASE WHEN st<>'INQUIRY' THEN (ed-((n%180)+12))::timestamp AT TIME ZONE 'Asia/Seoul' END,CASE WHEN st IN ('CONFIRMED','COMPLETED') THEN (ed-((n%180)+7))::timestamp AT TIME ZONE 'Asia/Seoul' END,CASE WHEN st='CANCELLED' THEN (ed-((n%180)+6))::timestamp AT TIME ZONE 'Asia/Seoul' END,ed,'BNQ-'||lpad((1+n%5)::text,2,'0'),CASE n%5 WHEN 0 THEN 'WEDDING' WHEN 1 THEN 'CONFERENCE' WHEN 2 THEN 'MEETING' WHEN 3 THEN 'CORPORATE_EVENT' WHEN 4 THEN 'SOCIAL_EVENT' ELSE 'SOCIAL_EVENT' END,(20+n%380)*180000,CASE WHEN st='CANCELLED' THEN (20+n%380)*18000 ELSE 0 END,20+n%380,CASE WHEN st='COMPLETED' THEN 15+n%360 END,CASE WHEN n%5=0 THEN 'DIRECT' WHEN n%5=1 THEN 'WEB' WHEN n%5=2 THEN 'AGENCY' WHEN n%5=3 THEN 'MICE' ELSE 'CRM' END,CASE WHEN n%3=0 THEN 'MICE_SALES' WHEN n%3=1 THEN 'WEDDING_SALES' ELSE 'EVENT_SALES' END,st,ed,ed+(1+n%3),60+n%50,70+n%50,CASE WHEN st='COMPLETED' THEN 5+n%45 ELSE 0 END,CASE WHEN st='CANCELLED' THEN 2+n%10 ELSE 0 END,'SYNTHETIC_ACTUAL_LIKE',false,true,timestamptz '2026-08-01 00:00:00+09' FROM s;
WITH b AS (SELECT banquet_event_id,product_code,product_category,booking_status,event_date,expected_guests FROM banquet_bookings WHERE property_id='SYNTHETIC_HOTEL_001')
INSERT INTO banquet_revenue(property_id,revenue_id,banquet_event_id,recognized_date,product_code,product_category,revenue_amount,reversal_amount,cost_amount,revenue_status,data_period_status,is_forecast,is_synthetic,source_updated_at)
SELECT 'SYNTHETIC_HOTEL_001','BR-'||substring(banquet_event_id from 4),banquet_event_id,event_date,product_code,'FOOD_BEVERAGE',CASE WHEN booking_status='COMPLETED' THEN expected_guests*180000 WHEN booking_status='CANCELLED' THEN 0 ELSE expected_guests*180000 END,CASE WHEN booking_status='CANCELLED' THEN expected_guests*180000 ELSE 0 END,expected_guests*90000,CASE WHEN booking_status='COMPLETED' THEN 'RECOGNIZED' WHEN booking_status='CANCELLED' THEN 'REVERSED' ELSE 'EXPECTED' END,'SYNTHETIC_ACTUAL_LIKE',false,true,timestamptz '2026-08-01 00:00:00+09' FROM b;
